### ISSUE TITLE
would you be open to letting me take over the npm package name for cobalt?

### ISSUE THREAD

**Issue by mreinstein** [gsamokovarov/cobalt#2]
Hi @gsamokovarov, 

I noticed you haven't been publishing to this npm module in a long time, and I'm working on a new open source project for the web; a web gpu based renderer.  I'd like to use the name cobalt, but I probably won't do it unless I can use the npm package name.

Here's a link to my project if it's any interest:  https://gist.github.com/mreinstein/197f804964b1a44611b0c4afe64dd736

Anyway, thanks for your time!

**Comment by gsamokovarov** [comment]
Hey, thank you so much for asking! While this package has clearly stagnated, I do like the cobalt name and would like to keep it for the time being.

But please, don't let that stop you from doing your OSS!
